POST http://localhost:8081/login
Content-Type: application/json

{
  "username": "nils",
  "password": "11334"
}

###

POST http://localhost:8081/verify
Content-Type: application/json

{
  "token": "eyJhbGciOiJSUzUxMiJ9.eyJzdWIiOiJ7XCJpZFwiOlwiVTFcIixcInVzZXJuYW1lXCI6XCJuaWxzXCIsXCJuYW1lXCI6XCJOaWxzIEhhcnRtYW5uXCIsXCJlbWFpbFwiOlwia29udGFrdEBuaWxzaGFydG1hbm4ubmV0XCIsXCJyb2xlc1wiOltcIlJPTEVfVVNFUlwiXX0iLCJpYXQiOjE2NDE0MjU1NjYsImV4cCI6MTY0MTQzMjc2Nn0.uHtx5YHhSn4lpcmr2_Ol8G5_AzPgLAHP6bCVjxM3Q0fr8NL8GyFtf0FAafWTob48hMN1WQPBjW3HWfXL8c5wvP-i8Iu_vZ6IlltEPk__bAcXcwFuIlFQrVGZpBik-0qgDefb5sIPirvODLNB21-mY7Wrr765-G5wweEMuExzPL4A8d5NvUMTEhRFyBRhi2yFaXEDHSewk8l01NOfuaNXxQI_cS_0_5EQ8zGLIknqV7qRybXsNYte2dbdAriqN0CPZ9nyTysLA5b_bRpPPwuH_e7QSby5Rbp7GaR2oOYXCvazBH3otGcibF72EOtVg1QZr8bR_kjCBXqBSlVt5XNMPg"
}

###

GET http://localhost:8080/ciao
Authorization: Bearer eyJhbGciOiJSUzUxMiJ9.eyJzdWIiOiJ7XCJpZFwiOlwiVTFcIixcInVzZXJuYW1lXCI6XCJuaWxzXCIsXCJuYW1lXCI6XCJOaWxzIEhhcnRtYW5uXCIsXCJlbWFpbFwiOlwia29udGFrdEBuaWxzaGFydG1hbm4ubmV0XCIsXCJyb2xlc1wiOltcIlJPTEVfVVNFUlwiXX0iLCJpYXQiOjE2NDEzNjk4NDcsImV4cCI6MzIzMjk4Nzk4N30.cXJh6llnkkYKRVXdtPCbjWhnEshbI1LnMVc9aZpwzk5j16EC3pLU5A5kgwH4JIZvl5aoMBfW9Wsdgll79kFY22bQvUQIGnZTyn9LZVFKWtyXttq4ZdA4eP64yQkcVRFoD3kCWSLRCzK97z4moGbhqfHGB1MjPvuYS7-SsdTtGGmit9w4jsaIHgisO5v8V9yMFsdYvQdNbzRMXTE6svLbLsVyCS5cA9-BycCvy5kNA2DTNPHZOZAFPqFEe3jbHUetmgXSSA2uEZyOUrMCxtSoVjS7vld1OKZZ1Z946Oj8rXbMz3O-4Ht8slEr5CX1ENB4MEIyBOZc8NuZ-iLFUuLJTA

###

GET http://localhost:8081/public-key